---
output: pdf_document
---

The ultimate goal is to find a research design that will allow us to identify how changes in sales tax rates affect prices for consumers. We want to start with the most basic case and build up to something that we can implement on a larger scale.

The first case we want to deal with is one county, one product. Then we can see how prices change for that single county
after the implementation of the tax. The example I choose for this scenario is Maricopa County, AZ (`fips_state = 04`; `fips_county = 013`). The reason for Maricopa County is that Arizona still taxes grocery items, so all items are taxable at the same rate. The grocery item I first looked at was refrigerated milk (`product_module_code = 3625`). However, we appear to have no data on milk sales in
Maricopa county, so I switch to toilet paper (`product_module_code = 7260`). (Note: we appear to have no data on Maricopa county at all...)


We first examine the **post-tax** price response of Arizona's June 2010 tax increase, when sales tax increased by 0.1%, on post-tax prices in Maricopa county.

# Note that I should create a function that allows the state, county, and product to be an input, and then creates output/graph based on these limited inputs #
```{r}
one_product_one_county()
```

We now examine the post-tax **normalized** price response of Maricopa county for all goods.

We now examine the post-tax price response of all counties in Arizona for milk only.

We now examine the post-tax price response of all counties in Arizona for all goods.
